apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-models
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1200Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-triton-models
